### PR TITLE
Side Specific Infinite Repair #731

### LINKED ISSUE #731: Side Specific Infinite Repair
Suggestion:

Change https://github.com/ArmaLife/Framework/blob/master/Altis_Life.Altis/Config_Master.hpp#L115 to an array for all 4 sides, allowing servers to choose if a specific side has infinite repair, useful for medics, ADAC, etc.

### PR DESCRIPTION
**Pull request by cammygames**
Resolves #731

### CODE REVIEW

**Comment by sargken** [comment]
A switch statement for the playersides?

**Comment by tshowler1** [comment]
It says "This branch has no conflicts with the base branch" 

When I added this to my mission, I got " config : some input after EndOfFile "
Searched the logs, and it said the config file couldnt be found, and was unable to connect to database.

Removed the update, and now I don't get the error, and I can connect to the database.

Just a heads up!

**Comment by Jawshy** [comment]
Tested and not working. 

Config_Master.hpp: 
```hpp
    vehicle_infiniteRepair[] = {false, false, true, false};
```

Toolkit is not removed upon repair for civilian or police when it should be removed.

**Comment by BoGuu** [comment]
@Jawshy 

https://github.com/ArmaLife/Framework/commit/6e70557bf3ab15da4266cf5a827123a9a98b6008

**Pull request merged**
