### PR TITLE
Fixed Tempest not mining oil + rocks

### PR DESCRIPTION
**Pull request by GetSomePanda**
For some reason it was counting the _resourceCfg instead of the
_mineralsCfg for the minerals statement.

### CODE REVIEW

**Comment by BoGuu** [comment]
There is a slightly easier way to fix this, and I see the issue, I'll post again shortly

**Comment by GetSomePanda** [comment]
Not sure that there is an easier way to fix this as all it was doing was counting the wrong array when it should have counted the right one. This fixes issues with adding new items to gather onto the list, but if there is an easier way to fix it, I'll be interested to see it.

**Comment by BoGuu** [comment]
@GetSomePanda 

No need to make new variables!

https://github.com/ArmaLife/Framework/commit/4c60304e49ebe35d53dbf78052a133fc9873792c

Thanks for the spot/help.

**Comment by GetSomePanda** [comment]
Thanks man appreciate it, also I was wondering if i should make a pull request for it or is it something you guys don't need ?

**Pull request closed without merging**
