### PR TITLE
Spyglass Update APEX

### PR DESCRIPTION
**Pull request by Heavybob**
Fixed spyglass patchlist for apex.
Included updated patchlist script.

### CODE REVIEW

**Comment by Jawshy** [comment]
Didn't format it into multiple lines. :(

**Comment by Heavybob** [comment]
FUCK YOUR MULTIPLE LINES!

**Comment by Jawshy** [comment]
No pull 4 u.

**Comment by Heavybob** [comment]
I am not putting the damn thing into multiple lines

**Comment by Heavybob** [comment]
it will work either way without or with multiple lines. if you don't like it use word wrap.

**Comment by Heavybob** [comment]
I made the pull because nobody gives a damn about apex. If you don't apply this patch or at least modify it to your standards of multiple lines of bollox then people will just have to deal with the bullshit of having no spyglass.

**Comment by Heavybob** [comment]
Killermachine99 - Today at 5:06 PM
hey can u help me

Heavy_Bob - Today at 5:06 PM
what do you need


Killermachine99 - Today at 5:08 PM
my spyglass is not working right i try youtube and reinstall mission file and edit spyglass file but it do not like my server for some reason
i am wondering can u some how to send me a custom spyglass?

Heavy_Bob - Today at 6:06 PM
https://github.com/ArmaLife/Framework/pull/871
GitHub
Spyglass Update APEX by Heavybob · Pull Request #871 · ArmaLife/...
Fixed spyglass patchlist for apex. Included updated patchlist script.

I have make the patch
doubt it will be committed
but it does fix the issue

Killermachine99 - Today at 6:09 PM
k thx man for help my server would not be up with out u

https://www.youtube.com/watch?v=WlMIDRFSBRo

**Comment by GamesTrap** [comment]
if i use this my client crashes at the spawn menu. CLIENT: Exception code: 0000DEAD  at 74CCDAE8

**Comment by NiiRoZz** [comment]
Why you don't use pushback inside function to recup all config, it's 2x faster than set

**Pull request closed without merging**
