### PR TITLE
No more server side localizations 

### PR DESCRIPTION
**Pull request by DardoTheMaster**
I don't know who put those localize there. 
I 've just integrated the calls with the broadcast function.

### CODE REVIEW

**Comment by Jawshy** [comment]
When selling a vehicle at the chop shop the titleText reads: `You have sold a <number> for $` E.g.: `You have sold a 650 for $`. 

No issues with life_server/Functions/Systems/fn_spawnVehicle.sqf or life_server/Functions/Systems/fn_vehicleStore.sqf.

**Comment by DardoTheMaster** [comment]
Well that's weird..

**Comment by BoGuu** [comment]
You have removed a lot of formats

**Comment by Jawshy** [comment]
@danielstuart14, why was this merged when above I said there was an issue?

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Framework/commit/8aaa290579f62062bd10393a8bbc8f74a894523d

**Pull request merged**
