### PR TITLE
NPC protection at cleanup

### PR DESCRIPTION
**Pull request by Kimax89**
Makes sure that NPC protected vehicles dont get removed by the cleanup.

### CODE REVIEW

**Comment by BoGuu** [comment]
Sorry when is this the case? What scenario?

**Comment by Kimax89** [comment]
i have a drug dealer that drives around and his car is being deleted by cleanup.
I have cars at the carshop to showoff, but those are being taking by cleanup too.

I allready added the option to NPC protect vehicles here: #509

**Comment by BoGuu** [comment]
Okay, sounds good. You are using exitWith from the forEach scope, this isn't a good idea. Can you please add it to the if check? for example:

`if(!(_veh getVariable "NPC") && {_vehicleClass in ["Car","Air","Ship","Armored","Submarine"]}) then {`

**Comment by Kimax89** [comment]
or put everything inside a bracket with ` if(!(_veh getVariable "NPC") then {run the rest of the script};`
In that way it will only run the check on all the vehicle that dosnt have the NPC protection, and therefor never delete a NPC protected vehicle.

**Comment by BoGuu** [comment]
@Kimax89 

That would require that you define the "NPC" variable on absolutely every vehicle, so just check if it's defined and then equal to true, and add a variable to the if check.

**Comment by Kimax89** [comment]
@BoGuu wouldnt this be a better solution? ` if(!isNil {_veh getVariable "NPC"} && {_veh getVariable "NPC"}) then {_protect = true;} else {_protect = false;}; `

**Comment by Liam0** [comment]
woulden't this whole thing be better in ur own files considering its not a part of this mission?

**Comment by BoGuu** [comment]
@Liam0 

It's already been pulled into the framework, so I don't seem any harm in making it work properly, unless we remove it all.

@Kimax89 

That statement is equivalent, except without the else, the code probably runs faster, tit for tat.

**Comment by Liam0** [comment]
@BoGuu 2 variables has been pulled into the framework for some reason yes. but its not part of this mission what he describes about his npc's driving around cars and displaying cars at the vendors. so it's rather pointless and silly to have in the framework. thats all i meant

**Comment by sargken** [comment]
No it should be added in because its already in the framework and documentation can be supplied to owners so they can add there own.

**Comment by Kimax89** [comment]
The resson why i added this, was to give server owners the ability to add npc vehicle into the mission with ease.

**Comment by BoGuu** [comment]
@Liam0 

I like the idea of giving people the option to void cleanups/scripts on certain vehicles, as long as it's documented, seems like a standard logical feature.

**Pull request closed without merging**
