### PR TITLE
Stringtable fixes (mostly german)

### PR DESCRIPTION
**Pull request by setoy**

### CODE REVIEW

**Comment by Jawshy** [comment]
Why is `STR_MAR_Sofia_Freight_Yard` added? I can't see it used any where else in the mission files.

**Comment by setoy** [comment]
I've got errors in my RPT because of the missing resource entry. That's why I've added it. Since then the errors are gone.

		class Item89
		{
			dataType="Marker";
			position[]={25943.723,17.185471,21374.17};
			name="Kavala Freight Yard_1_1_1_1_1";
			text="@STR_MAR_Sofia_Freight_Yard";
			type="mil_dot";
			colorName="ColorUnknown";
			angle=304.08701;
			id=89;
		};

I think this might be exclusive to our mission. Feel free to remove it :)

**Comment by Jawshy** [comment]
It must be as this repo's mission.sqm lacks that item. Could you please remove it from your pull as that's easier and cleaner than removing it after this is merged.

**Comment by setoy** [comment]
Done. Btw: Italian too features € instead of $...

**Comment by Jawshy** [comment]
Thanks. I'll fix that in my pull.

**Pull request merged**
