### PR TITLE
Pay Bail -> Fixed

### PR DESCRIPTION
**Pull request by DarkSilencerZA**
Can't believe this wasn't tested..

### CODE REVIEW

**Comment by BoGuu** [comment]
Kinda doesn't make much difference anyway

**Comment by DarkSilencerZA** [comment]
lol.. it's been tested on a live server. Wasn't working at all before. Working now though!

**Comment by Jawshy** [comment]
This fixed worked for me. 

Could you resolve the conflict, please. Then we can merge.

**Comment by sargken** [comment]
How can there be a conflict just manually merge it.

**Comment by DarkSilencerZA** [comment]
https://gyazo.com/db7e72d86b297b0f5c5c242800a425f3

**Comment by DarkSilencerZA** [comment]
db7e72d86b297b0f5c5c242800a425f3

**Pull request merged**
