### PR TITLE
#615 - Headless Client Cleanup

### PR DESCRIPTION
**Pull request by BoGuu**
This attends to that mentioned in #615. Any infinite loops, i.e cleanups, will only run on EITHER the HC or the server, depending if a HC is connected. 

Furthermore, the server will run without issues if you have, or have not, or have never had a headless client connected, unlike before. This has in theory removed the need for the config option for HC, however I left 'HeadlessSupport' for those picky people who want the extra performance boost from not adding the PV eventhandlers (could be changed in the future though I guess).

The server will also print a repeated systemChat if the Headless client runs into any issues, but will still run as normal. I.e, the HC can't connect to the DB (before this would stop the player initialisation).

From my testing, animal ownership seems to be working fine, and I will review the huntingzone script shortly, as it really sucks.

I'll write up some multi HC stuff later on, done with HC for a lil' bit!

I need people to thoroughly test this before a merge due to the amount of changes made :+1:

### CODE REVIEW

**Comment by Kimax89** [comment]
Why does this need testing?
And does this have any impact on performance?

**Comment by BoGuu** [comment]
@Kimax89 

Everything needs testing, it's better to have multiple say it works as intended for reliability.
This will increase performance when a HC is connected, when one isn't the performance is the same.

**Comment by NiiRoZz** [comment]
All work.

**Comment by danielstuart14** [comment]
10:42:52 Error in expression <rver_isReady","_extDB_notLoaded"];

if (life_HC_isActive) then {
_server_isReady>
10:42:52   Error position: <life_HC_isActive) then {
_server_isReady>
10:42:52   Error Undefined variable in expression: life_hc_isactive
10:42:52 File mpmissions\__CUR_MP.Altis\core\init.sqf, line 12

**Comment by tkcjesse** [comment]
Why do we just shove this shit in... ? The dude asks to test it. We question why and just merge it. I'd love to know if we actually tested this or just looked at it and said. Yep. Good. Lets go!

**Comment by BoGuu** [comment]
@danielstuart14 

Okay, are you connecting instantly? It just seems like the server is yet to broadcast. I'll put a fix in for that shortly.

**Pull request merged**
