### PR TITLE
Dynamicmarket

### PR DESCRIPTION
**Pull request by Wackbatt**

### CODE REVIEW

**Comment by dbenson24** [comment]
I'm so confused

**Comment by Wackbatt** [comment]
same

**Comment by CarlosHingel** [comment]
Just a question... 

Is the Dynamic market going to get pushed to the framework\master when it's finished? I think this a must have! Because without Dynamic market the players always gather\farm the same thing, which get 's boring with time because they will always make the same routes and etc.

**Comment by tkcjesse** [comment]
No this has been discussed. Some people like an economy like this and some don't. This is something owners can add on their own.

**Comment by Tankiouse** [comment]
@tkcjesse so owners struggle in adding it... is the a tutorial/guided for 4.4??? I have looked every where even tried this one and can't get it to work... Doesn't give errors in the logs...

**Comment by dbenson24** [comment]
@Tankiouse come to the gitter if you want help, make sure you check the masterconfig and turn the market on.

You really think it won't make it in even with config options that let you pretend it's not there by just setting them to false? @tkcjesse

**Comment by CarlosHingel** [comment]
I agree with @Tankiouse and @dbenson24 

Dynamic market should be added to the framework but be disabled by default but with an option to enable it on the master config! Because this way The server owners that don't want it will simple keep it disable and the ones that want it will enable it without the need to struggle with editing many files to add it.

**Comment by Tankiouse** [comment]
@dbenson24 hahaha when you think you set it to true but then double check and realise that it was false all along...Seems to be working just need to test it now :P

**Comment by BoGuu** [comment]
If you can't copy and paste files, and make slight changes, you shouldn't be a server owner. We can add 1000 new features, and leave the toggle inside the master config, the same shit applies. Learn what you're doing, instead of asking for it to be placed into the next release. There are PLENTLY of brainless tutorials for these kinds of things

**Comment by CarlosHingel** [comment]
@BoGuu 

I'm not asking this to be implemented in the next released, i simple asked a question about the fate of this dynamic market and the question it self initiate a discussion about the importance of it and the possibility of it being implemented or not in the future. 

It's not just a question of copy and paste, being lazy, not knowing what are you doing and this being another simple feature or not!

This is not a feature like the 1000 others ones that people ask to be implemented but are not that important and that you can easily find it on the forum(all versions of dynamic market there are outdated! And you have to go through several forum pages to find the solutions)! This feature is a gameplay change one! It makes less linear, repetitive(same resource, same fields, routes and etc) and it will add a bit more of challenge to the task of gathering resources because the player will not be always going to gather the same resource always(he will need to get more licenses, go to more parts of the map and etc)

I revived this not because i being lazy and wanting the files given to me so that i can just throw them on my server! I already "copied, pasted and did slight changes" and implemented @dbenson24 market on my test server! The reason i  revived this, because like i said, in my opinion this feature is important!

You don't need to be this "hostile" over a simple discussion about an important feature(my opinion). I understand that dumb requests, features and etc are made all the time here by lazy people that don't want to even try and learn and that you guys are tired of answering to them! If this feature would also be the same case, i wouldn't comment here to restart this.

Anyway... if you guys think this is not important, then i'm sorry that I've restart a discussion about it here. Just let this go to limbo.

Thank you @dbenson24 and @tkcjesse for developing a new and up to date dynamic market :)

**Pull request closed without merging**
