### PR TITLE
Handle Blasting Charge Explosion Over Server / HC

### PR DESCRIPTION
**Pull request by GetSomePanda**

### CODE REVIEW

**Comment by Jawshy** [comment]
Your changes will require updates to the BattlEye filters, specifically remoteExec and setVariable. If you are unsure how to update these then I can do it and give you the files. 

Also, your comments are intended with tabs rather than the required 4 spaces.

**Comment by GetSomePanda** [comment]
Added BattlEye Filters + I fixed the tabs instead of spaces issue  here: https://github.com/ArmaLife/Framework/pull/787/commits/71f6d186346e03756db8d2213ca33852f3140c7b

**Comment by Jawshy** [comment]
Thanks. Regarding the indentation, I was referring to: [life_hc/MySQL/General/fn_handleBlastingCharge.sqf, line 2-5](https://github.com/GetSomePanda/Framework/blob/c65ad1cbb7e380a70fa65e95349e1eecacad610a/life_hc/MySQL/General/fn_handleBlastingCharge.sqf#L2-L5) and [life_server/Functions/Systems/fn_handleBlastingCharge.sqf, lines 2-5](https://github.com/GetSomePanda/Framework/blob/c65ad1cbb7e380a70fa65e95349e1eecacad610a/life_server/Functions/Systems/fn_handleBlastingCharge.sqf#L2-L5).

**Comment by GetSomePanda** [comment]
Oops, all fixed now thanks for notifying me.

**Comment by Jawshy** [comment]
No worries. 

Also, as the blasting charge is now handled over the server, `!=Bo_GBU12_LGB_MI10` could be removed from [createVehicle.txt](https://github.com/ArmaLife/Framework/blob/6aee5f447cdbd1e4df6048a8740a8f95c198c032/BEFilters/createVehicle.txt), yes?

**Comment by GetSomePanda** [comment]
Yes, as BattlEye does not listen to what the server does, only the clients.

**Comment by Jawshy** [comment]
> Would you like me to remove it for you ?

Add a commit to your pull that removes it.

**Comment by GetSomePanda** [comment]
Done.

**Comment by BoGuu** [comment]
What you've done here, from the quick skim through I've had, is nothing.

You're still waiting on some variable to be set before initiating the explosion, which was the exact problem. All you've done is just increased the amount of people PVAR'ing said variable to include all the cops too. If they all disconnect, nothing happens. Also, if the HC loses connection, this all goes to shit aswell.

**Comment by GetSomePanda** [comment]
Yes, but if all cops leave you can't open the fed box so no point blowing it up when you can't open it.
You can always add the timer to the handleBlastingCharge instead of the explode var if its a big deal.

The HC has to disconnect within the 5 minutes of explosion time which really shouldn't happen but that can be changed.

**Comment by BoGuu** [comment]
Firstly, we could move player into the targets of remoteExec, and remove the spawn. Secondly, I would remove the HC part all together, it's not going to help performance at all really, and does pose a problem if the HC did disconnect, which is more than plausible.

Also, make sure both events line up, as the timer clientside is more than likely to not hit 0 as the server creates the explosion.

**Comment by GetSomePanda** [comment]
Right, I got it, I will do this now.

**Comment by GetSomePanda** [comment]
Also i will have a look at the times linking up in awhile then will put it in if there has to be changes.

**Comment by GetSomePanda** [comment]
Working fine now, bomb goes off on time aswell, tested and works good.

**Comment by BoGuu** [comment]
[] remoteExec ["life_fnc_demoChargeTimer",[west,player]];

Said that to remove the need for two lines ^

**Comment by GetSomePanda** [comment]
Didn't think of that, thanks.

**Comment by Jawshy** [comment]
Tested with life_server (not life_hc). No issues found. As of https://github.com/ArmaLife/Framework/pull/787/commits/999892d4521a9b542fa992d9cbe559786c328ab7.

**Comment by GetSomePanda** [comment]
@Jawshy Its ready to go, we removed HC support as it is more likely to end up causing more problems. Should be ready to be put in.

**Comment by Jawshy** [comment]
There are conflict which need to be resolved before this can be merged.

**Comment by GetSomePanda** [comment]
@Jawshy Yep done it. Ready to go.

**Pull request merged**
