### PR TITLE
MACRO Removal

### PR DESCRIPTION
**Pull request by tkcjesse**
Removed a bunch of pointless simple macros:

#define SVAR_MNS
#define SVAR_UINS
#define SVAR_PNS
#define GVAR_MNS
#define GVAR_UINS
#define CASH
#define BANK
#define GANG_FUNDS
#define GVAR
#define SVAR
#define GVAR
#define SVAR
#define RIFLE
#define RIFLE_ITEMS
#define PISTOL
#define PISTOL_ITEMS
#define LAUNCHER

### CODE REVIEW

**Comment by NiiRoZz** [comment]
I think for me it's fucked merge, MACRO is the Best think because, MACRO do optimization

**Comment by tkcjesse** [comment]
How is it "optimized", we're including it on every single file... It's basically an extra step to add an ALIAS. Please explain...

https://i.gyazo.com/ef1ea9b71a2d002284c8d76800e7ebb5.png

**Comment by BoGuu** [comment]
And for everybody who used their own variable for cash in the macro? They have go change it all, seems a bit silly.

**Comment by tkcjesse** [comment]
Find and Replace is not hard to use? lol

**Comment by NiiRoZz** [comment]
I think ok for grpplayer, but MACRO do optimization because the client only load one time functions and you don't need to replace all files for Bank or Cash, One or top MACRO need Remove but don't all of this

**Comment by tkcjesse** [comment]
I'd love to see execution times on this matter or actual documentation to support that using the preprocessor macros gives "optimization". Do as you please. Revert it back if you feel the macros are necessary then.

**Comment by NiiRoZz** [comment]
"Pre-compilation by the game engine can save up 20x the amount of time processing"

**Comment by BoGuu** [comment]
If you are under the impression that the macros are making it unreadable, what stops any competent person from using the macros file as an index? I agree some of the macros are not too needed, but you are cutting off compatibility with a couple of the only macros a community would choose to change. Sure you can use f/r to change things, but you are making people change content in almost every update they do, so the idea of making it 'easier' in essence, isn't.

**Comment by tkcjesse** [comment]
@NiiRoZz  So you're telling me that by doing getVariable as  GVAR we're saving 20x the amount of time processing?

**Comment by baua1310** [comment]
Also most editing tools for sqf have inbuild syntax autocompletion, so it's faster to use the normal commands than using macros.

**Comment by NiiRoZz** [comment]
It's not me spoke that, it's bohemia, If you want very optimize, just precompile all .sqf inside mission and you will have more fps, i think here, you add content all update, for me this version of Tonic doesn't need update. For me this repository don't need update now, just battleye filter update or spyglass. This repository go to a fucked mission. In 2 mounth all functions in tuto altisliferpg will going to main mission. But Tonic would juste a base mission and after community update what he want. I think this repository need update with only Daniel do commits or other, don't have 5 people to do that. Just need optimization and update of spyglass or Battleye. When i see this repository before and now. Now it's fucked mission when all men give this functions or add functions for main mission, but now mission have 10 functionnality, it's nice but Now i think stop this add content, don't touch. Fix bug and only That

**Comment by BoGuu** [comment]
@tkcjesse 

And the 'releases' will still require people go through and change things, most people will only use x% of an update, nobody is forcing people to use 100% of the content provided for a certain version.

**Comment by tkcjesse** [comment]
@NiiRoZz, yes. I think you forgot to read the 2 lines or so above that... Where it mentions "excessive cleverness" which is essentially what most of these macros are...
https://i.gyazo.com/defc6a3d74910ed95e961d202e6bc585.png

**Comment by NiiRoZz** [comment]
For resume my message : @danielstuart14, if you continue like that you will kill Tonic's first goal, a simple task, and communities add what they want in their mission to differentiate it from each other. If this continues, I think withdraw from the staff of this repository.

**Comment by BoGuu** [comment]
@tkcjesse 

The macros in Altis Life don't fall under the "excessive cleverness" bracket.

"It's also an act of hubris - programmers doing things because they want to show how clever they are rather than getting the job done" is not really the case in Altis Life is it?

**Comment by tkcjesse** [comment]
Lol, I'm done arguing something so stupid with you people.

**Comment by BoGuu** [comment]
@tkcjesse 

It's creating work for communities that wasn't really needed, ofcourse they can still differentiate themselves, but making something simpler and at the same time doing the opposite, seems silly. Macros have been embedded for far too long in this to just say fuck it.

**Comment by ColinM9991** [comment]
Looks like a nice little fork will be made soon from the arrogance of few people.

Like BoGuu said, a lot of macros are pointless and the ones removed are the pointless ones.

As for "20x faster", I've never heard such shit. PreProcessor directives are just that, for the preprocessing and compiling. Why don't we just define entire script files if it's "20x" faster and then call those script flies?

**Comment by tkcjesse** [comment]
Yeah.... lol

**Pull request merged**
