### PR TITLE
Rework the fulstation service

### PR DESCRIPTION
**Pull request by Kimax89**
Instead of searching at different locations, then lets search for every single fuel feeder there is and apply the action to it.

Even feeders that is placed in the editor will be affected, so if you want another place to fuel your truck, just place another feeder. its just that single.

### CODE REVIEW

**Comment by tkcjesse** [comment]
How about performance wise... Whats the execution time of this?

**Comment by BoGuu** [comment]
That is my concern ^. If you're already in the editor what stops you from running that snippet again? It's produces a copy paste array.

**Comment by tkcjesse** [comment]
In plain eden editor with no other scripts running in single player the command took..  ~173.667ms

**Comment by NiiRoZz** [comment]
If you want use this command, just addaction in MP With remoteExec and jip true and Will only take 173 ms for the server

**Comment by NiiRoZz** [comment]
I think this pull request is stupid and if you have added fuel stations in eden, just load mission with this fuel station and use my script inside description and that's all

**Comment by Kimax89** [comment]
Sorry for doing this pull, but i really could'nt feel any performance decrease by running this.
My point in this script was to add the action, to every single fuel station there is, in 1 go.

**Comment by BoGuu** [comment]
Without visually watching for a performance decrease, behind the scenes, as mentioned, it's taking 173ms to run, of which I imagine would be drastically lower on a lower quality PC. If you had 50 people with bad PC's all trying to connect at the same time, I have a feeling it COULD (maybe) have a slight affect on server performance. 

That being said, people don't add petrol pumps into the map every day, if at all, so the time it'd take them to just re-update the array wouldn't really be a pain if they had to. IMO.

Maybe looking into a non clientside JIP solution would be better, as NiiRoZz said, I can think of a couple that would be more elegant.

**Comment by BoGuu** [comment]
Until something that has performance in mind is made, I'll close this for now.

**Pull request closed without merging**
