### PR TITLE
BEFilters: Update: Data Logging Exceptions, misc

### PR DESCRIPTION
**Pull request by Jawshy**
Added new exceptions to the BattlEye filters for when the settings under Config_Master.hpp → Data Logging Settings are set to true. Also fixes a script.txt exception. 

Everything tested except actions that require two players (such as robbing, etc.). Should work fine though. 

ATTENTION: Only merge if https://github.com/ArmaLife/Framework/pull/679 is merged else some exceptions won't work. 

Remember to use "squash and merge". 

##### Config_Master.hpp: 
- Re-wrote the comments for the various Data Logging Settings. 

##### mpEventHandler.txt: 
- Log everything. 
- Log to .log and console files, and kick for everything except exactly `_this call fn_whoDoneit`. 

##### publicVariableVal.txt: 
- Added exceptions for the Data Logging Settings (advanced_log and player_moneyLog). 
  - `!"arrested ."` - Cop arrests. 
  - `!"picked up [\d]{1,3} [a-z ]{1,17}"` - Items picked up off of the ground. 
  - `!"created a gang named: [a-z0-9_ ]{1,32} for \$[\d]"` - Gang creations. 
  - `!"(bought|sold) a house for \$"` - House purchase and sale. 
  - `!"chopped vehicle ."` - Vehicle chopping. 
  - `!"(bought|chopped|sold) vehicle ."` - Vehicle purchase and sale
  - `!"(deposited|picked up|robbed|transferred|withdrew) \$"` - Money picked up off the ground. Player robbery, bank/gang deposit/transfer/withdraw. 

##### remoteExec.txt: 
- Log everything except exactly `_this call fn_whoDoneit`. 
  - It will be logged in mpEventHandler.log. 
- Added `_this call fn_whoDoneit` as an exact exception. 

##### scripts.txt: 
- Fixed: Line 8, exception for `W_O_O_K_I_E`.

### CODE REVIEW

**Comment by BoGuu** [comment]
7 kicks and logs to both .log and console files no? What's the need for the 1 ""?

**Comment by tkcjesse** [comment]
@Jawshy if you want to make a new comment for the BEfilter logging in the Mconfig, feel free. Since no one seems to understand it.

**Comment by Jawshy** [comment]
@BoGuu 
The `1 ""` is so BE logs `_this call fn_whoDoneit`. The second line will not log it because it's an exception on that line. Same reason why a lot of the other filters have `1 ""` and then `5 "" ![some exception] [...]`.

**Comment by BoGuu** [comment]
@Jawshy 

It slipped my mind you'd want to log _this call fn_whoDoneit aswell.

Is this all working, confirmation?

**Comment by Jawshy** [comment]
> Is this all working, confirmation?

@BoGuu, re-tested with the latest changes. Working as intended.

**Pull request merged**
