### PR TITLE
Spyglass: Don't throw errors if var is Nil.

### PR DESCRIPTION
**Pull request by danielstuart14**
I wasn't able to test it.

### CODE REVIEW

**Comment by BoGuu** [comment]
The variable won't appear in allVariables if it's nil to begin with. The problem with the bail stuff was it was defined, then undefined mid flight

**Comment by BoGuu** [comment]
This branch is out-of-date with the base branch
Merge the latest changes from master into this branch.

**Comment by tkcjesse** [comment]
Was the changes fine otherwise?

**Comment by BoGuu** [comment]
It will be fine yeh

**Comment by BoGuu** [comment]
Sort your branch out already so I can hit merge! :+1:

**Pull request merged**
