### PR TITLE
Fix No entry 'MapView.LineMarker'

### PR DESCRIPTION
**Pull request by harmdhast**
Fixed this.Ty again Bohemia

### CODE REVIEW

**Comment by Liam0** [comment]
isn't it already fixed ?https://github.com/ArmaLife/Framework/commit/d5fb79a1f5546a9fe6fbc431de773267bd4efac8

**Comment by harmdhast** [comment]
No

**Comment by BoGuu** [comment]
Please look at the latest dev build files before pulling in future

**Comment by harmdhast** [comment]
How do you explain I still had the problem ?
The modifications in the common.hpp didn't worked for me.

**Comment by BoGuu** [comment]
All the stuff you put into your spawnSelection.hpp is already defined in common.hpp, MapView inherits from Life_RscMapControl, you don't need to define it all again. Nobody else has this issue, it's been fixed.

**Comment by harmdhast** [comment]
If you say so.

**Pull request closed without merging**
