### PR TITLE
Params

### PR DESCRIPTION
**Pull request by BoGuu**
I have no life, please check.

### CODE REVIEW

**Comment by tkcjesse** [comment]
About time you did something.

**Comment by Jawshy** [comment]
For documentation, could you please describe the purpose(s) of these changes?

**Comment by tkcjesse** [comment]
Because params double as private basically.

**Comment by danielstuart14** [comment]
working?

**Comment by Jawshy** [comment]
I'll test this pull momentarily.

**Comment by Jawshy** [comment]
The following message was written to the client/local.rpt file on the spawn select screen and when the player click a spawn option: 
```
14:27:34 Error in expression <ition.sqf"







disableSerialization;
params [
["_control",controlNull,[contro>
14:27:34   Error position: <params [
["_control",controlNull,[contro>
14:27:34   Error Type Array, expected Number
14:27:34 File mpmissions\__CUR_MP.Altis\dialog\function\fn_setMapPosition.sqf, line 9
```
Note that players can still spawn just fine, but the map will not zoom over to the spawn position. 

The following message was written to the client/local.rpt file when opening a virtual item shop: 
```
14:34:10 Error in expression <(missionConfigFile >> "VirtualShops" >> life_shop_type)) exitWith {closeDialog 0>
14:34:10   Error position: <life_shop_type)) exitWith {closeDialog 0>
14:34:10   Error Undefined variable in expression: life_shop_type
14:34:10 File mpmissions\__CUR_MP.Altis\core\shops\fn_virt_update.sqf, line 20
14:34:10 Error in expression <velType",
"_levelValue",
"_levelMsg"
];
params [
"life_shop_npc",
"",
"",
"life_>
14:34:10   Error position: <params [
"life_shop_npc",
"",
"",
"life_>
14:34:10   Error Local variable in global space
14:34:10 File mpmissions\__CUR_MP.Altis\core\shops\fn_virt_menu.sqf, line 21
```
Shop lists no virtual items. 

The following message was written to the client/local.rpt file when buying an item from a weapon shop: 
```
14:36:39 Error in expression <[];
_magazines = [];
_return = [];

if (_section isEqualTo "") then {
_section =>
14:36:39   Error position: <_section isEqualTo "") then {
_section =>
14:36:39   Error Undefined variable in expression: _section
14:36:39 File mpmissions\__CUR_MP.Altis\core\functions\fn_fetchCfgDetails.sqf, line 47
```
Items do not correctly display (no icon, same items have names, other do not), have incorrect prices, and do not correctly purchase (no item; no cash taken, hint says item was purchased).

**Comment by Jawshy** [comment]
The following message was written to the server.rpt file when renting or buying a vehicle:
```
2016/06/01, 14:43:00 Error in expression <t.sqf"







private["_input","_arr"];
params [
"_uid",
["_side",sideUnknown,[s>
2016/06/01, 14:43:00   Error position: <params [
"_uid",
["_side",sideUnknown,[s>
2016/06/01, 14:43:00   Error Params: Type Object, expected Number
2016/06/01, 14:43:00 File life_server\Functions\Systems\fn_keyManagement.sqf, line 9
```
Vehicle can be unlocked and locked, and key appears on the key chain. However, checking registration will cause the vehicle to be deleted for "having no information and probably being spawned in with cheats." 

Cannot create a gang. Hint says "Sending information to server, please wait." No RPT errors.

**Comment by BoGuu** [comment]
Will review this soon, seems to be a rather annoying but large issue.

**Pull request closed without merging**
