### PR TITLE
Added Alarm at federal Reserve

### PR DESCRIPTION
**Pull request by Kimax89**
This is just a simple trigger that sounds an alarm SFX.
The trigger activate when a civilian enters the dome.

This works in single player, but havent been tested in Multiplayer.

### CODE REVIEW

**Comment by Jawshy** [comment]
I think it would be preferred if any alarm implemented would activate upon bolt cutting the door rather than being proximity based.

**Comment by Heavybob** [comment]
Rather it be proximity. Make it so!

**Comment by Heavybob** [comment]
@Jawshy If its bolt cutting that triggers, how does it turn off?

**Comment by sargken** [comment]
@Heavybob "The alarm would also need to stop once police repaired all doors (end of robbery)."

**Comment by Heavybob** [comment]
Alarm works wonders. Manually merged into my own build.

**Comment by Liam0** [comment]
im with jawshy on this one to be honest. this would just be an anoying alarm.

**Comment by Jawshy** [comment]
Will this pull request be merged? I would like to make a pull request, but it will conflict with this one.

**Comment by DarkSilencerZA** [comment]
Again though, this is all custom stuff that should on on the onus of the server owner to implement. As was the suicide vest.

**Pull request closed without merging**
