### PR TITLE
Update fn_houseMenu.sqf

### PR DESCRIPTION
**Pull request by fresqo**
just to block medics from buying houses or bringing up the menu

### CODE REVIEW

**Comment by CamaroZ** [comment]
Wouldn't it be better than fn_buyHouse? Because sometimes people can add any medical action in the menu ... As garage or other things like that. My opinion ...

**Comment by fresqo** [comment]
In my opinion it would be better to not have the menu come up at all for medics. May the powers above please let me know which they would like and i can amend. also if they would rather isEqualTo instead of ==.. i think i remember someone talking about this a little while back.

**Comment by danielstuart14** [comment]
Switch to isEqualTo 
Yeah, it's better to it just doesn't show up

**Comment by tkcjesse** [comment]
Please add a space in if ()

**Pull request merged**
