### PR TITLE
Remove Suicide Vest

### PR DESCRIPTION
**Pull request by tkcjesse**
Removes everything suicide vest related that was inserted. Well, quite
certain it's "everything".

https://github.com/ArmaLife/Framework/commit/06f7629364db231ae978234ff9a1fd07d4a036e5
https://github.com/ArmaLife/Framework/commit/ea2743b38e8f944a749ffffeee44c8ec23b4fede
https://github.com/ArmaLife/Framework/commit/90c7b13fc9687964ca44ec2246ab1587f8881991
https://github.com/ArmaLife/Framework/commit/05969255ca83777e86d045744639fae1f4a08e39
https://github.com/ArmaLife/Framework/commit/e6d44278135d360f9e7019f51e03439989c5cf3c
https://github.com/ArmaLife/Framework/commit/5592d1d20c926dea51d7b6acc3a39a0c4c4c7261
https://github.com/ArmaLife/Framework/commit/22860fa3847e014a761034829baf65864076200d
https://github.com/ArmaLife/Framework/commit/551af3fdd8de494aa60fca2c9904fa3c6efaf2d4
https://github.com/ArmaLife/Framework/commit/250961ac522f25bffc01eef02d3f44a4d56a434c

### CODE REVIEW

**Comment by sargken** [comment]
Why?

**Comment by sargken** [comment]
Why don't you guys make an optional folder and set it up so ppl can add things like this by copy pasting.

**Comment by danielstuart14** [comment]
not something that should be added to framework.
Thx @tkcjesse

**Comment by tkcjesse** [comment]
And this is something thats all over the web and probably altisliferpg.com  and its as simple as copy and paste. The setup to support an optional folder would be dirty and not clean at all.

**Comment by sargken** [comment]
I just have never seen it before that's why I ask. What I'm saying is make another Project Besides Framework Named like Optional Addons or Scripts or whatever and ppl can make them and put them there with install instructions or what not. It would be separate from this but it would also be more organized than altisliferpg.com. Whats your thoughts on that.

**Comment by BoGuu** [comment]
@sargken 

I already mentioned making a branch to deal with that in another issue, it could run purely off config settings, it's a nice little project. But perhaps getting the framework to a high standard all round would be a good to do before hand?

**Comment by sargken** [comment]
Well I wouldn't make a branch because branches can get "lost" in a since but make another Project Under the ArmaLife Name. So people could make contributions for scripts there and if they are good enough for this we can always merge them here. The Framework is already a high standard we can keep saying that it needs to be better but it will always be improved upon and regardless the old scripts will have to be updated either now or later.  I just think having a separate project with instructions for ppl to submit things to it would be a cool idea.

**Comment by BoGuu** [comment]
@sargken 

The framework is not even close to being a high standard, unfortunately. It would be a good idea of course, a new repo or branch, it matters not. But the main attention should be the framework.

**Comment by sargken** [comment]
Yes for the main guys the focus should be framework but like this piece it will be "lost" in everything now that its reverted which I agree with. Say some servers want it and a nice place to go and look we could say is this other "branch,repo". Just some thoughts.

**Comment by BoGuu** [comment]
@tkcjesse 
I honestly think this is a much nicer layout:

class xxxx
{
   //code
};

than 

class xxxx {

Any reason to remove it?

**Comment by danielstuart14** [comment]
that's just cosmetic, I actually prefer in-line class/bracket, since it makes the file smaller.
But, as I said, just cosmetic.

**Comment by sargken** [comment]
@danielstuart14 I agree with you.

**Comment by tkcjesse** [comment]
@BoGuu I personally hate:
``class {
};``

I much would rather have:
``class 
{
};``

As that is the "proper" way, that I have to do at work and such.
My reason for changing it was simply to match ALL the other code like that. As Dan brought up it does compact things a bit, however I do feel it's harder to distinguish stuff sometimes when there is a lot of nested if's.

**Pull request merged**
