### PR TITLE
not need global side dude

### PR DESCRIPTION
**Pull request by berkaslan**

### CODE REVIEW

**Comment by NiiRoZz** [comment]
WTF ARE YOU DOING ?

**Comment by berkaslan** [comment]
Just tried something to edit :vertical_traffic_light: sorry i think i spammed.

**Comment by NiiRoZz** [comment]
It's not that but you do lights in local but it's beacon men, needed to be global ..

**Comment by berkaslan** [comment]
thats maybe fine on this, but when you have had more players as +100 you on @ASM- FPS  shows down with money police/medic cars when they are opens the lights. sorry if im wrong on this.
so I just wrote need to be "Local" this side. 
:zap:

**Comment by NiiRoZz** [comment]
Yes but if you put local, so just disabled it, it's the same

**Comment by berkaslan** [comment]
you are knows better than me allreay,  but just wrote it what I tried and saw on asm fps graphics :)

**Comment by NiiRoZz** [comment]
Yes but when you put local light only the guys activate it see it, so if you want tu put local need to execute on all client so better to just createvehicle

**Comment by berkaslan** [comment]
How only the guys activate it see it... Everybody can see it, but nvm. :} just works fine on me and wanted to tell it.

**Comment by tkcjesse** [comment]
Yeah. Not sure why this is a thing...

**Pull request closed without merging**
